### ISSUE TITLE
Estrutura projeto

### ISSUE THREAD

**Issue by osmarbraz** [IgorHenM/A3_Emprestimo_de_Ferramentas#11]
A estrutura do repositório está incorreta. 
A pasta src deve estar na raiz do repositório. Não deve existir a pasta [a3_programacao](https://github.com/IgorHenM/A3_Emprestimo_de_Ferramentas/tree/main/a3_programacao) pois é o próprio nome do repositório.

**Comment by IgorHenM** [comment]
Resolvido.
